# Generated by Django 4.0.8 on 2023-07-14 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=300, unique=True)),
                ('poster', models.ImageField(max_length=400, null=True, upload_to='posters/%Y/%m/%d')),
                ('description', models.TextField(blank=True, default='')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('type', models.CharField(blank=True, max_length=200)),
                ('release_year', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
