# Generated by Django 4.0.8 on 2023-07-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='status',
            field=models.CharField(blank=True, choices=[('unknown', 'unknown'), ('ongoing', 'ongoing'), ('completed', 'completed')], max_length=100),
        ),
    ]
